Tracking:
  Repositories:
    - source: "github"
      owner: "moov-io"
      name: "ach"
  Queue:
    QueueName: "oss_repos"
    ConnectionString: "postgres://community_commits:secret@127.0.0.1:5432/community_commits?sslmode=disable"
    RescanEvery: "24h"
