name: Refresh Data

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  deployments: write
  contents: write

jobs:
  run:
    name: Refresh Data
    runs-on: ubuntu-latest

  steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: Check out code
      uses: actions/checkout@v4

    - name: Switch to master
      run: |
        git fetch origin
        git checkout master

    - name: Refresh Data
      run: make run-example
      env:
        COMMUNITY_COMMITS_GITHUB_API_KEY: ${{ secrets.COMMUNITY_COMMITS_GITHUB_API_KEY }}

    - name: Commit changes
      run: |
        git config user.name "moov-bot"
        git config user.email "oss@moov.io"
        git add ./docs/
        git commit -m "chore: updating networks data" || echo "No changes to commit"
        git push origin master
